# Generated by Django 4.2.20 on 2025-04-08 08:55

from django.db import migrations, models
import pantry.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField(default=pantry.models.two_weeks_from_now)),
            ],
        ),
    ]
